### ISSUE TITLE
Issue with serializing Joda date

### ISSUE THREAD

**Issue by binurajagopal1212** [jerrinot/subzero#18]
Hello,
 I am facing an issue with Joda date time when using subzero-all.jar. Version that is being used is 0.7
As mentioned in subzero ReadMe,  i have used 
SubZero.useAsGlobalSerializer(config);
HazelcastClient.newHazelcastClient(config);
config is an instance of Hazelcast ClientConfig class.
Since we are using Joda LocalDate and DateTime in application, we need to have that also serialized.
For this, i created a subzero-serializers.properties and added below lines:-
org.joda.time.LocalDate=de.javakaffee.kryoserializers.jodatime.JodaLocalDateSerializer
org.joda.time.DateTime=de.javakaffee.kryoserializers.jodatime.JodaDateTimeSerializer
org.joda.time.LocalDateTime=de.javakaffee.kryoserializers.jodatime.JodaLocalDateTimeSerializer
We are using version 0.42 of https://github.com/magro/kryo-serializers. 
Ours is a web application that is deployed in JBoss 7. I am getting this deployment exception.
I am using Java 8, JBoss 7, Hazelcast 3.8.1, info.jerrinot.subzero-all 0.7  and de.javakaffee.kryo-serializers 0.42 versions
Could you please let me know what I am doing incorrectly?
	at com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.build(DefaultSerializationServiceBuilder.java:231)

	... 44 more

Caused by: java.lang.ClassCastException: de.javakaffee.kryoserializers.jodatime.JodaLocalDateSerializer cannot be cast to info.jerrinot.subzero.relocated.com.esotericsoftware.kryo.Serializer

	at info.jerrinot.subzero.internal.PropertyUserSerializer.addNewSerializer(PropertyUserSerializer.java:127)

	at info.jerrinot.subzero.internal.PropertyUserSerializer.readLineAndRegister(PropertyUserSerializer.java:70)

	at info.jerrinot.subzero.internal.PropertyUserSerializer.initCustomSerializers(PropertyUserSerializer.java:54)

	at info.jerrinot.subzero.internal.PropertyUserSerializer.<init>(PropertyUserSerializer.java:41)

	at info.jerrinot.subzero.Serializer.<init>(Serializer.java:10)

	... 51 more

**Comment by jerrinot** [comment]
Hi, 

You can try to use the - subzero-core instead of subzero-all

**Comment by binurajagopal1212** [comment]
@jerrinot , thank you for that. Using subzero-core helped in getting past this exception.
Tried setting subzero.buffer.size.kb to different values. But no luck.
I have set this in a properties file and passing it to JBoss VM using -D mechanism. Hope this is right
2017-08-11 13:22:10,804 INFO  [stdout] (default task-1) 					8934837073 - Unexpected exception caught on REST api! User/client message includes unique server error #SE1502437930782: com.hazelcast.nio.serialization.HazelcastSerializationException: com.esotericsoftware.kryo.KryoException: Buffer underflow.


2017-08-11 13:22:10,804 INFO  [stdout] (default task-1) com.hazelcast.nio.serialization.HazelcastSerializationException: com.esotericsoftware.kryo.KryoException: Buffer underflow.

2017-08-11 13:22:10,804 INFO  [stdout] (default task-1) 	at com.hazelcast.internal.serialization.impl.SerializationUtil.handleException(SerializationUtil.java:61) ~[hazelcast-3.8.1.jar:3.8.1]

2017-08-11 13:22:10,807 INFO  [stdout] (default task-1) 	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:190) ~[hazelcast-3.8.1.jar:3.8.1]

2017-08-11 13:22:10,807 INFO  [stdout] (default task-1) 	at com.hazelcast.client.spi.ClientProxy.toObject(ClientProxy.java:187) ~[hazelcast-client-3.8.1.jar:3.8.1]

2017-08-11 13:22:10,809 INFO  [stdout] (default task-1) 	at com.hazelcast.client.proxy.ClientMapProxy.get(ClientMapProxy.java:288) ~[hazelcast-client-3.8.1.jar:3.8.1]


2017-08-11 13:22:10,899 INFO  [stdout] (default task-1) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_92]

2017-08-11 13:22:10,899 INFO  [stdout] (default task-1) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_92]

2017-08-11 13:22:10,899 INFO  [stdout] (default task-1) 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]

2017-08-11 13:22:10,899 INFO  [stdout] (default task-1) Caused by: com.esotericsoftware.kryo.KryoException: Buffer underflow.

2017-08-11 13:22:10,899 INFO  [stdout] (default task-1) 	at com.esotericsoftware.kryo.io.InputChunked.readChunkSize(InputChunked.java:84) ~[kryo-4.0.0.jar:?]

2017-08-11 13:22:10,899 INFO  [stdout] (default task-1) 	at com.esotericsoftware.kryo.io.InputChunked.fill(InputChunked.java:70) ~[kryo-4.0.0.jar:?]

2017-08-11 13:22:10,899 INFO  [stdout] (default task-1) 	at com.esotericsoftware.kryo.io.Input.require(Input.java:196) ~[kryo-4.0.0.jar:?]

2017-08-11 13:22:10,899 INFO  [stdout] (default task-1) 	at com.esotericsoftware.kryo.io.Input.readVarInt(Input.java:373) ~[kryo-4.0.0.jar:?]

2017-08-11 13:22:10,899 INFO  [stdout] (default task-1) 	at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:127) ~[kryo-4.0.0.jar:?]

2017-08-11 13:22:10,899 INFO  [stdout] (default task-1) 	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:693) ~[kryo-4.0.0.jar:?]

2017-08-11 13:22:10,899 INFO  [stdout] (default task-1) 	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:804) ~[kryo-4.0.0.jar:?]

2017-08-11 13:22:10,909 INFO  [stdout] (default task-1) 	at info.jerrinot.subzero.internal.strategy.GlobalKryoStrategy.readObject(GlobalKryoStrategy.java:28) ~[subzero-core-0.7.jar:?]

2017-08-11 13:22:10,909 INFO  [stdout] (default task-1) 	at info.jerrinot.subzero.internal.strategy.KryoStrategy.read(KryoStrategy.java:79) ~[subzero-core-0.7.jar:?]

2017-08-11 13:22:10,909 INFO  [stdout] (default task-1) 	at info.jerrinot.subzero.AbstractSerializer.read(AbstractSerializer.java:30) ~[subzero-core-0.7.jar:?]

2017-08-11 13:22:10,909 INFO  [stdout] (default task-1) 	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48) ~[hazelcast-3.8.1.jar:3.8.1]

2017-08-11 13:22:10,909 INFO  [stdout] (default task-1) 	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:184) ~[hazelcast-3.8.1.jar:3.8.1]

2017-08-11 13:22:10,909 INFO  [stdout] (default task-1) 	... 86 more

**Comment by jerrinot** [comment]
do you have a reproducer? is this error specific to REST interface? is it working fine with Java client?

**Comment by binurajagopal1212** [comment]
Exception seems to be getting thrown immediately after findOne() is called. We are using Spring Data Repository to data access.
One other thing I want to add is that application works fine with and without cache. Members of Hazelcast technical team suggested us to use Kyro serialization and Subzero libs since Java serialization is known to be slow.
Unfortunately I am unable to come up with a sample app right now. 
Since this is a web app and deployed in Jboss, I am assuming that this cannot be thread safety issue.
2017-08-11 15:09:51,570 INFO  [stdout] (default task-3) com.hazelcast.nio.serialization.HazelcastSerializationException: com.esotericsoftware.kryo.KryoException: Buffer underflow.
2017-08-11 15:09:51,570 INFO  [stdout] (default task-3) 	at com.hazelcast.internal.serialization.impl.SerializationUtil.handleException(SerializationUtil.java:61) ~[hazelcast-3.8.1.jar:3.8.1]
2017-08-11 15:09:51,570 INFO  [stdout] (default task-3) 	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:190) ~[hazelcast-3.8.1.jar:3.8.1]
2017-08-11 15:09:51,570 INFO  [stdout] (default task-3) 	at com.hazelcast.client.spi.ClientProxy.toObject(ClientProxy.java:187) ~[hazelcast-client-3.8.1.jar:3.8.1]
2017-08-11 15:09:51,570 INFO  [stdout] (default task-3) 	at com.hazelcast.client.proxy.ClientMapProxy.get(ClientMapProxy.java:288) ~[hazelcast-client-3.8.1.jar:3.8.1]
2017-08-11 15:09:51,570 INFO  [stdout] (default task-3) 	at com.hazelcast.spring.cache.HazelcastCache.lookup(HazelcastCache.java:139) ~[hazelcast-spring-3.8.1.jar:3.8.1]
2017-08-11 15:09:51,570 INFO  [stdout] (default task-3) 	at com.hazelcast.spring.cache.HazelcastCache.get(HazelcastCache.java:57) ~[hazelcast-spring-3.8.1.jar:3.8.1]
2017-08-11 15:09:51,570 INFO  [stdout] (default task-3) 	at org.springframework.cache.interceptor.AbstractCacheInvoker.doGet(AbstractCacheInvoker.java:68) ~[spring-context-4.1.4.RELEASE.jar:4.1.4.RELEASE]
2017-08-11 15:09:51,570 INFO  [stdout] (default task-3) 	at org.springframework.cache.interceptor.CacheAspectSupport.findInCaches(CacheAspectSupport.java:461) ~[spring-context-4.1.4.RELEASE.jar:4.1.4.RELEASE]
2017-08-11 15:09:51,570 INFO  [stdout] (default task-3) 	at org.springframework.cache.interceptor.CacheAspectSupport.findCachedItem(CacheAspectSupport.java:432) ~[spring-context-4.1.4.RELEASE.jar:4.1.4.RELEASE]
2017-08-11 15:09:51,570 INFO  [stdout] (default task-3) 	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:333) ~[spring-context-4.1.4.RELEASE.jar:4.1.4.RELEASE]
2017-08-11 15:09:51,570 INFO  [stdout] (default task-3) 	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:299) ~[spring-context-4.1.4.RELEASE.jar:4.1.4.RELEASE]
2017-08-11 15:09:51,570 INFO  [stdout] (default task-3) 	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61) ~[spring-context-4.1.4.RELEASE.jar:4.1.4.RELEASE]
2017-08-11 15:09:51,570 INFO  [stdout] (default task-3) 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.1.4.RELEASE.jar:4.1.4.RELEASE]
2017-08-11 15:09:51,570 INFO  [stdout] (default task-3) 	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207) ~[spring-aop-4.1.4.RELEASE.jar:4.1.4.RELEASE]
2017-08-11 15:09:51,570 INFO  [stdout] (default task-3) 	at com.sun.proxy.$Proxy171.findOne(Unknown Source) ~[?:?]
2017-08-11 15:09:51,570 INFO  [stdout] (default task-3) 	at com.cgi.t360.tps.model.service.impl.core.AbstractEntitySvcImpl.retrieveEntity(AbstractEntitySvcImpl.java:902) ~[tps-model-0.0.1-SNAPSHOT.jar:?]

**Comment by binurajagopal1212** [comment]
@jerrinot Hello, just want to inform you one more thing.
We are using both Spring cache abstraction and Hibernate L2 caching in our application. For both these, we are using Hazelcast as the provider.
For Spring cache, methods like findOne and findBySomeFields etc are annotated with Spring @Cacheable annotation.
For HL2 caching, entities and collections (if required) are annotation with hibernate @Cache annotation.
What I found just now was that, request works fine for methods that are Spring cached.   Buffer underflow exception appears only while retrieving entities that are marked with Hibernate @Cache.

**Comment by binurajagopal1212** [comment]
Hi @jerrinot , please close this issue.
While trying to create a sample app, I had messed up quite a few things.
I had uncommented Hibernate @Cache from my domain class. At the same time Spring Data JPA findOne had Spring @Cacheable annotation. Looks like repository.findOne() was all going mad with both these annotations. Now everything works fine.
Thanks a lot for all your response and please accept my sincere apologies for wasting your time on a non-issue
Thanks & best regards,
Binu Rajagopal

**Comment by binurajagopal1212** [comment]
Hi @jerrinot , one more question.
Looks like subzero and cryo should  be used only when caching is enabled. We have a switch using which can be enable/disabled.
In most developer laptops caching needs to be switched off.
Would you suggest adding Subzero.SubZero.useAsGlobalSerializer(config); only if caching is enabled?
Thanks,
Binu

**Comment by jerrinot** [comment]
I don't know your design, but I assume when you have caching disabled then `SubZero.useAsGlobalSerializer(config);` has no effect on your application.
