### ISSUE TITLE
Serialization issue with java.util.Date

### ISSUE THREAD

**Issue by binurajagopal1212** [jerrinot/subzero#20]
Hello,
  I am using subzero library in my application.I have created a file called `subzero-serializers.properties` and have added below 3 lines. This works fine
```
org.joda.time.LocalDate=de.javakaffee.kryoserializers.jodatime.JodaLocalDateSerializer
org.joda.time.DateTime=de.javakaffee.kryoserializers.jodatime.JodaDateTimeSerializer
org.joda.time.LocalDateTime=de.javakaffee.kryoserializers.jodatime.JodaLocalDateTimeSerializer
```

But when I add serializer for  java.util.Date in this file, I am getting exceptions like below. Tried two different ways. 

1. DateSerializer
2.java,util.Date=de.javakaffee.kryoserializers.
. With this I am getting
```
Caused by: java.lang.IllegalStateException: Serializer DateSerializer does not have expected method 'registerSerializers()': 

	at info.jerrinot.subzero.internal.PropertyUserSerializer.addNewSpecialSerializer(PropertyUserSerializer.java:90)

	at info.jerrinot.subzero.internal.PropertyUserSerializer.readLineAndRegister(PropertyUserSerializer.java:73)

	at info.jerrinot.subzero.internal.PropertyUserSerializer.initCustomSerializers(PropertyUserSerializer.java:54)

	at info.jerrinot.subzero.internal.PropertyUserSerializer.<init>(PropertyUserSerializer.java:41)

	at info.jerrinot.subzero.Serializer.<init>(Serializer.java:10)

	... 56 more

Caused by: java.lang.NoSuchMethodException: de.javakaffee.kryoserializers.DateSerializer.registerSerializers(com.esotericsoftware.kryo.Kryo)

	at java.lang.Class.getMethod(Class.java:1786)

	at info.jerrinot.subzero.internal.PropertyUserSerializer.addNewSpecialSerializer(PropertyUserSerializer.java:83)

	... 60 more
```

Can you please let me know what is it that I am doing wrong?
Few  more information regarding the application
1. Application is deployed as war in JBoss EAP 7.0
2.This war contains a jar. subzero-serializers.properties is placed in CLASSPATH of this project
3. We are using Java 8
4. I am using below libs in my maven
			<dependency>
				<groupId>info.jerrinot</groupId>
				<artifactId>subzero-core</artifactId>
				<version>0.7</version>
			</dependency>

			<dependency>
				<groupId>de.javakaffee</groupId>
				<artifactId>kryo-serializers</artifactId>
				<version>0.42</version>
			</dependency>
Thanks in advance for any help

**Comment by binurajagopal1212** [comment]
Is there any help I can get with the above issue w.r.t java.util.Date? Am I doing any incorrect configuration?

**Comment by jerrinot** [comment]
@binurajagopal1212: Hazelcast has an optimized serializer for `j.u.Date` and it's not possible to override it. I reckon Hazelcast internals rely on it. There is nothing Subzero can do about it.
