### ISSUE TITLE
Is asList from Arrays supported?

### ISSUE THREAD

**Issue by karussell** [jerrinot/subzero#28]
Thanks a lot for your nice tool. The integration was really simple. I'm using 0.8 and hazelcast 3.11.

Now I'm getting the following NPE:

```
Caused by: java.lang.NullPointerException: null
	at java.util.Arrays$ArrayList.size(Arrays.java:3818)
	at java.util.AbstractList.add(AbstractList.java:108)
	at info.jerrinot.subzero.relocated.com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:134)
	at info.jerrinot.subzero.relocated.com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:40)
	at info.jerrinot.subzero.relocated.com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:731)
	at info.jerrinot.subzero.relocated.com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
```

I suspect this is from the ArrayList that I got via `Arrays.asList()` but adding `Arrays.asList().getClass()` to the `useForClasses` list did not help with this issue.

**Comment by karussell** [comment]
A temporary workaround is to replace the Arrays.asList with:

new ArrayList<>(Arrays.asList("some", "items"));

**Comment by jerrinot** [comment]
probably related to https://github.com/EsotericSoftware/kryo/issues/461

**Comment by jerrinot** [comment]
@karussell:

can you try to add this dependency into your project:
```xml
        <dependency>
            <groupId>de.javakaffee</groupId>
            <artifactId>kryo-serializers</artifactId>
            <version>0.42</version>
        </dependency>
```
and create a file `subzero-serializers.properties`  with `ArraysAsListSerializer`. This file should be on a classpath of your project.

**Comment by karussell** [comment]
Thanks! So this is more a kryo problem?

**Comment by jerrinot** [comment]
yeah, some classes are not supported out-of-the-box by Kryo. You can use the 3rd party serializer as shown above.
