### ISSUE TITLE
MultipleEntryBackupOperation throws NullPointerException when using SubZero as GlobalSerializer

### ISSUE THREAD

**Issue by MojoManagement** [jerrinot/subzero#33]
Hi,

I am using Hazelcast 3.11.1 with SubZero 3.9 and configured it with SubZero.useAsGlobalSerializer(config);

When using SubZero, I got the log full with these exceptions:

`java.lang.NullPointerException: null
	at com.hazelcast.map.AbstractEntryProcessor$EntryBackupProcessorImpl.processBackup(AbstractEntryProcessor.java:83)
	at com.hazelcast.map.impl.operation.EntryOperator.process(EntryOperator.java:314)
	at com.hazelcast.map.impl.operation.EntryOperator.operateOnKeyValueInternal(EntryOperator.java:181)
	at com.hazelcast.map.impl.operation.EntryOperator.operateOnKey(EntryOperator.java:166)
	at com.hazelcast.map.impl.operation.MultipleEntryBackupOperation.run(MultipleEntryBackupOperation.java:48)
	at com.hazelcast.spi.impl.operationservice.impl.operations.Backup.run(Backup.java:158)
	at com.hazelcast.spi.Operation.call(Operation.java:170)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:208)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:197)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:413)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:153)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:123)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110)`

Please take a look at this

Regards

**Comment by ohadpinch** [comment]
Reproducer at: https://github.com/hazelcast/hazelcast/issues/15018

**Comment by jerrinot** [comment]
thanks for the report. at first glance it appears it could be related to: https://github.com/EsotericSoftware/kryo/issues/320

**Comment by jerrinot** [comment]
hi @ohadpinch,

I pushed an experiment into master. Try to build the latest master and add `serializerConfigurers=EnableSyntheticFields` into your `subzero-serializers.properties` file.

**Comment by jerrinot** [comment]
@MojoManagement: can you try the latest master? thanks!

**Comment by MojoManagement** [comment]
@jerrinot I will try to check it tomorrow

**Comment by jerrinot** [comment]
@MojoManagement: did you have a chance to check it?

**Comment by MojoManagement** [comment]
I have not found any problems, but I was not able to reproduce this at all
