### ISSUE TITLE
Custom Kryo serializer for unmodificable collections

### ISSUE THREAD

**Issue by llaros** [jerrinot/subzero#46]
Hello,
 
I've read https://github.com/jerrinot/subzero/issues/8 and therefore placed `subzero-serializers.properties` file with ```
UnmodifiableCollectionsSerializer```
as its content. 

Project dependencies

```
                  <dependency>
			<groupId>info.jerrinot</groupId>
			<artifactId>subzero-all</artifactId>
			<version>0.10</version>
		</dependency>
		<dependency>
			<groupId>de.javakaffee</groupId>
			<artifactId>kryo-serializers</artifactId>
			<version>0.45</version> <!-- tried also with 0.49 same problem -->
		</dependency>
```

hazelcast.xml with following element
```
    <serialization>
        <serializers>
            <global-serializer override-java-serialization="true">info.jerrinot.subzero.Serializer</global-serializer>
        </serializers>
    </serialization>
```

But got following exception on hz node startup:

```
Caused by: java.lang.IllegalStateException: Serializer UnmodifiableCollectionsSerializer does not have expected method 'registerSerializers()': 
obh-cache-hz-cluster_1                    |     at info.jerrinot.subzero.internal.PropertyUserSerializer.addNewSpecialSerializer(PropertyUserSerializer.java:90)
obh-cache-hz-cluster_1                    |     at info.jerrinot.subzero.internal.PropertyUserSerializer.readLineAndRegister(PropertyUserSerializer.java:73)
obh-cache-hz-cluster_1                    |     at info.jerrinot.subzero.internal.PropertyUserSerializer.initCustomSerializers(PropertyUserSerializer.java:54)
obh-cache-hz-cluster_1                    |     at info.jerrinot.subzero.internal.PropertyUserSerializer.<init>(PropertyUserSerializer.java:41)
obh-cache-hz-cluster_1                    |     at info.jerrinot.subzero.Serializer.<init>(Serializer.java:10)
```

I've decompiled UnmodifiableCollectionsSerializer and assured that it has
```
 public static void registerSerializers(Kryo kryo) {
        UnmodifiableCollectionsSerializer serializer = new UnmodifiableCollectionsSerializer();
        UnmodifiableCollectionsSerializer.UnmodifiableCollection.values();
        UnmodifiableCollectionsSerializer.UnmodifiableCollection[] var2 = UnmodifiableCollectionsSerializer.UnmodifiableCollection.values();
        int var3 = var2.length;

        for(int var4 = 0; var4 < var3; ++var4) {
            UnmodifiableCollectionsSerializer.UnmodifiableCollection item = var2[var4];
            kryo.register(item.type, serializer);
        }

    }
```

**Comment by llaros** [comment]
IMHO the problem lies with the expected Kryo object or more precisely its package `com.esotericsoftware.kryo.Kryo` vs `info.jerrinot.subzero.relocated.com.esotericsoftware.kryo.Kryo`

**Comment by llaros** [comment]
Problem solved with following dependencies

```
<dependency>
			<groupId>info.jerrinot</groupId>
			<artifactId>subzero-core</artifactId>
			<version>0.10</version>
		</dependency>
		<dependency>
			<groupId>de.javakaffee</groupId>
			<artifactId>kryo-serializers</artifactId>
			<version>0.45</version>
		</dependency>
		<dependency>
			<groupId>com.esotericsoftware</groupId>
			<artifactId>kryo</artifactId>
			<version>4.0.2</version>
		</dependency>
```

**Comment by llaros** [comment]
I've reopened just because I don't know whether or notshould subzero-all work out-of-the box with kryo-serializers.

**Comment by jerrinot** [comment]
hi, thanks for reporting this, your analysis looks correct. I'll check what to do about it.

**Comment by jerrinot** [comment]
Some more thoughts: Subzero-All could relocate Kryo dependencies, but keep Kryo itself in its original packages.
Why? Kryo depends on some fairly popular low-level infrastructure libraries, such as Asm or Objenesis. Not relocating them could lead to a bad JAR hell. Kryo itself is less popular and the risk of conflicts is lower. Not relocating it will allow 3rd party serializers to work. Thanks to @viliam-durina for the idea!
