### ISSUE TITLE
java.lang.ClassNotFoundException: sun.reflect.ReflectionFactory

### ISSUE THREAD

**Issue by omasseau** [jerrinot/subzero#82]
Running subzero on Wildlfy with JDK 11 I get this error : 

```
java.lang.ClassNotFoundException: sun.reflect.ReflectionFactory from [Module "deployment.AofWeb.war" from Service Module Loader]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:255)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at deployment.AofWeb.war//info.jerrinot.subzero.relocated.org.objenesis.instantiator.sun.SunReflectionFactoryHelper.getReflectionFactoryClass(SunReflectionFactoryHelper.java:54)
```

**Comment by omasseau** [comment]
Got the solution here : 

https://stackoverflow.com/a/51592708/1879731

Still I'm not sure using sun.reflect.ReflectionFactory is a good idea as starting from jdk 9 classes in the sun.* package should not be used : 

    The sun.* packages are not part of the supported, public interface.

    A Java program that directly calls into sun.* packages is not guaranteed to work on all Java-compatible platforms. In fact, such a program is not guaranteed to work even in future versions on the same platform.

See: https://openjdk.org/jeps/260

java.lang.reflect.* package should be used instead.
